const myAge = 24;
// This is a constant variable that is my age which is 24
let earlyYears = 2;
// This code for the earlyYears has the variable of 2 //
earlyYears *= 10.5;
let laterYears = myAge - 2;
// This is a variable that is called later years and will have a answer that is my age - 2 //
laterYears *= 4;
// The variable laterYears will be multiplied by 4 to calculate the number of dog years //
console.log(earlyYears);
console.log(laterYears);
let myAgeInDogYears = earlyYears + laterYears;
// This new variable myAgeInDogYears will be earlyYears + laterYears //
let myName = 'Gavin' .toLowerCase();
console.log(`My name is ${myName}. I am ${myAgeInDogYears} years old in dog years.`);
 